{{ if .Values.honeycomb.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "writekey-secret-name" . }}
  namespace: {{ .Release.Namespace }}
type: "Opaque"
data:
    key: {{ .Values.honeycomb.writekey | b64enc | quote }}
{{ end -}}
