# Service account for the agent
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "service-account-name" . }}
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Namespace }}:{{ include "service-account-name" . }}-observes-pods
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pod-observer
subjects:
- kind: ServiceAccount
  name: {{ include "service-account-name" . }}
  namespace: {{ .Release.Namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pod-observer
rules:
  - apiGroups:
    - "*"
    resources:
    - pods
    verbs:
    - list
    - watch
